version: '3'

services:
  front:
    build: .
    ports:
      - "8888:80"
    links:
      - mysql:mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=forum
